services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: pantech-web:latest
    container_name: pantech-web
    ports:
      - "160:80"
    restart: always
    networks:
      - pantech-network

networks:
  pantech-network:
    driver: bridge