version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: pantech-web:latest
    container_name: pantech-web
    ports:
      - "160:80"
    restart: always
    networks:
      - pantech-network
    volumes:
      - type: bind
        source: ./index.html
        target: /var/www/html/index.html
        read_only: true
      - type: bind
        source: ./styles.css
        target: /var/www/html/styles.css
        read_only: true
      - type: bind
        source: ./script.js
        target: /var/www/html/script.js
        read_only: true
      - type: bind
        source: ./images
        target: /var/www/html/images
        read_only: true

networks:
  pantech-network:
    driver: bridge 